package com.b2s.shop.common.order;

import java.util.Date;

public interface OrderLineIF {
	
    public Long getOrderId();
    public void setOrderId(Long orderId);
    public Integer getLineNum();
    public void setLineNum(Integer lineNum);
    public String getSupplierId();
    public void setSupplierId(String supplierId);
    public String getVarId();
    public void setVarId(String varId);
    public String getProgramId();
    public void setProgramId(String programId);
    public String getCategory();
    public void setCategory(String category);
    public String getSupplierOrderId();
    public void setSupplierOrderId(String supplierOrderId);
    public String getItemId();
    public void setItemId(String itemId);
    public String getName();
    public void setName(String name);
    public String getImageUrl();
    public void setImageUrl(String imageUrl);
    public String getColor();
    public void setColor(String color);
    public Integer getWeight();
    public void setWeight(Integer weight);
    public String getSize();
    public void setSize(String size);
    public String getAttr1() ;
    public void setAttr1(String attr1) ;
    public String getAttr2();
    public void setAttr2(String attr2);
    public String getAttr3();
    public void setAttr3(String attr3);
    public String getIsEligibleForSuperSaverShipping();
    public void setIsEligibleForSuperSaverShipping(String isEligibleForSuperSaverShipping) ;
    public Integer getQuantity();
    public void setQuantity(Integer quantity);
    public Integer getSupplierItemPrice() ;
    public void setSupplierItemPrice(Integer supplierItemPrice);
    public Integer getSupplierTaxPrice();
    public void setSupplierTaxPrice(Integer supplierTaxPrice);
    public Integer getB2sTaxPrice();
    public void setB2sTaxPrice(Integer b2sTaxPrice);
    public Integer getSupplierPerShipmentPrice();
    public void setSupplierPerShipmentPrice(Integer supplierPerShipmentPrice);
    public String getSupplierShippingUnit();
    public void setSupplierShippingUnit(String supplierShippingUnit);
    public Integer getSupplierShippingUnitPrice();
    public void setSupplierShippingUnitPrice(Integer supplierShippingUnitPrice);
    public Integer getSupplierSingleItemShippingPrice();
    public void setSupplierSingleItemShippingPrice(Integer supplierSingleItemShippingPrice);
    public Integer getSupplierShippingPrice();
    public void setSupplierShippingPrice(Integer supplierShippingPrice);
    public Double getConvRate() ;
    public void setConvRate(Double convRate);
    public Integer getTaxRate() ;
    public void setTaxRate(Integer taxRate);
    public Integer getB2sTaxRate() ;
    public void setB2sTaxRate(Integer b2sTaxRate);
    public Double getB2sItemMargin() ;
    public void setB2sItemMargin(Double b2sItemMargin);
    public Double getVarItemMargin();
    public void setVarItemMargin(Double varItemMargin);
    public Double getB2sShippingMargin();
    public void setB2sShippingMargin(Double b2sShippingMargin);
    public Double getVarShippingMargin();
    public void setVarShippingMargin(Double varShippingMargin) ;
    public Double getItemPoints();
    public void setItemPoints(Double itemPoints);
    public Double getTaxPoints();
    public void setTaxPoints(Double taxPoints) ;
    public Double getB2sTaxPoints();
    public void setB2sTaxPoints(Double b2sTaxPoints);
    public Double getShippingPoints();
    public void setShippingPoints(Double shippingPoints);
    public Integer getOrderLinePoints();
    public void setOrderLinePoints(Integer orderLinePoints) ;
    public Integer getB2sItemProfitPrice();
    public void setB2sItemProfitPrice(Integer b2sItemProfitPrice);
    public Integer getB2sTaxProfitPrice();
    public void setB2sTaxProfitPrice(Integer b2sTaxProfitPrice);
    public Integer getB2sShippingProfitPrice();
    public void setB2sShippingProfitPrice(Integer b2sShippingProfitPrice);
    public Integer getVarItemProfitPrice();
    public void setVarItemProfitPrice(Integer varItemProfitPrice);
    public Integer getVarTaxProfitPrice();
    public void setVarTaxProfitPrice(Integer varTaxProfitPrice) ;
    public Integer getVarShippingProfitPrice();
    public void setVarShippingProfitPrice(Integer varShippingProfitPrice);
    public Integer getVarOrderLinePrice();
    public void setVarOrderLinePrice(Integer varShippingProfitPrice);    
    public String getComment();
    public void setComment(String comment);
    public Date getCreateDate();
    public void setCreateDate(Date createDate);
    public Integer getOrderStatus();
    public void setOrderStatus(Integer orderStatus);
    public String getOrderLineType();
    public void setOrderLineType(String orderLineType);

    // ItemPriceAmount in original currency. We have to store it here so we can store it with order and it is needed from 
    // Super Saver calculation.
    public void setItemPriceOriginal(int ItemPriceOriginal);
    public Integer getItemPriceOriginal();
}
