package com.b2s.db.model;

import java.util.Date;

public class DemoUser extends DemoUserKey {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column demo_user.password
     *
     * @abatorgenerated Fri Oct 13 15:16:02 PDT 2006
     */
    private String password;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column demo_user.activeind
     *
     * @abatorgenerated Fri Oct 13 15:16:02 PDT 2006
     */
    private String activeind;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column demo_user.points
     *
     * @abatorgenerated Fri Oct 13 15:16:02 PDT 2006
     */
    private Integer points;

    /**
     * This field is to indicate if the user's balance was updated by a third-party app
     */
    private boolean updateBalance;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column demo_user.firstname
     *
     * @abatorgenerated Fri Oct 13 15:16:02 PDT 2006
     */
    private String firstName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column demo_user.lastname
     *
     * @abatorgenerated Fri Oct 13 15:16:02 PDT 2006
     */
    private String lastName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column demo_user.addr1
     *
     * @abatorgenerated Fri Oct 13 15:16:02 PDT 2006
     */
    private String addr1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column demo_user.addr2
     *
     * @abatorgenerated Fri Oct 13 15:16:02 PDT 2006
     */
    private String addr2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column demo_user.city
     *
     * @abatorgenerated Fri Oct 13 15:16:02 PDT 2006
     */
    private String city;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column demo_user.state
     *
     * @abatorgenerated Fri Oct 13 15:16:02 PDT 2006
     */
    private String state;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column demo_user.zip
     *
     * @abatorgenerated Fri Oct 13 15:16:02 PDT 2006
     */
    private String zip;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column demo_user.country
     *
     * @abatorgenerated Fri Oct 13 15:16:02 PDT 2006
     */
    private String country;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column demo_user.phone
     *
     * @abatorgenerated Fri Oct 13 15:16:02 PDT 2006
     */
    private String phone;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column demo_user.email
     *
     * @abatorgenerated Fri Oct 13 15:16:02 PDT 2006
     */
    private String email;
    
    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column demo_user.password
     *
     * @return the value of demo_user.password
     *
     * @abatorgenerated Fri Oct 13 15:16:02 PDT 2006
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column demo_user.password
     *
     * @param password the value for demo_user.password
     *
     * @abatorgenerated Fri Oct 13 15:16:02 PDT 2006
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column demo_user.activeind
     *
     * @return the value of demo_user.activeind
     *
     * @abatorgenerated Fri Oct 13 15:16:02 PDT 2006
     */
    public String getActiveind() {
        return activeind;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column demo_user.activeind
     *
     * @param activeind the value for demo_user.activeind
     *
     * @abatorgenerated Fri Oct 13 15:16:02 PDT 2006
     */
    public void setActiveind(String activeind) {
        this.activeind = activeind;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column demo_user.points
     *
     * @return the value of demo_user.points
     *
     * @abatorgenerated Fri Oct 13 15:16:02 PDT 2006
     */
    public Integer getPoints() {
        return points;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column demo_user.points
     *
     * @param points the value for demo_user.points
     *
     * @abatorgenerated Fri Oct 13 15:16:02 PDT 2006
     */
    public void setPoints(Integer points) {
        this.points = points;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column demo_user.firstname
     *
     * @return the value of demo_user.firstname
     *
     * @abatorgenerated Fri Oct 13 15:16:02 PDT 2006
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column demo_user.firstname
     *
     * @param firstName the value for demo_user.firstname
     *
     * @abatorgenerated Fri Oct 13 15:16:02 PDT 2006
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column demo_user.lastname
     *
     * @return the value of demo_user.lastname
     *
     * @abatorgenerated Fri Oct 13 15:16:02 PDT 2006
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column demo_user.lastname
     *
     * @param lastName the value for demo_user.lastname
     *
     * @abatorgenerated Fri Oct 13 15:16:02 PDT 2006
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column demo_user.addr1
     *
     * @return the value of demo_user.addr1
     *
     * @abatorgenerated Fri Oct 13 15:16:02 PDT 2006
     */
    public String getAddr1() {
        return addr1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column demo_user.addr1
     *
     * @param addr1 the value for demo_user.addr1
     *
     * @abatorgenerated Fri Oct 13 15:16:02 PDT 2006
     */
    public void setAddr1(String addr1) {
        this.addr1 = addr1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column demo_user.addr2
     *
     * @return the value of demo_user.addr2
     *
     * @abatorgenerated Fri Oct 13 15:16:02 PDT 2006
     */
    public String getAddr2() {
        return addr2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column demo_user.addr2
     *
     * @param addr2 the value for demo_user.addr2
     *
     * @abatorgenerated Fri Oct 13 15:16:02 PDT 2006
     */
    public void setAddr2(String addr2) {
        this.addr2 = addr2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column demo_user.city
     *
     * @return the value of demo_user.city
     *
     * @abatorgenerated Fri Oct 13 15:16:02 PDT 2006
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column demo_user.city
     *
     * @param city the value for demo_user.city
     *
     * @abatorgenerated Fri Oct 13 15:16:02 PDT 2006
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column demo_user.state
     *
     * @return the value of demo_user.state
     *
     * @abatorgenerated Fri Oct 13 15:16:02 PDT 2006
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column demo_user.state
     *
     * @param state the value for demo_user.state
     *
     * @abatorgenerated Fri Oct 13 15:16:02 PDT 2006
     */
    public void setState(String state) {
        if(state != null && !state.isEmpty()) {
            this.state = state;
        }
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column demo_user.zip
     *
     * @return the value of demo_user.zip
     *
     * @abatorgenerated Fri Oct 13 15:16:02 PDT 2006
     */
    public String getZip() {
        return zip;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column demo_user.zip
     *
     * @param zip the value for demo_user.zip
     *
     * @abatorgenerated Fri Oct 13 15:16:02 PDT 2006
     */
    public void setZip(String zip) {
        this.zip = zip;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column demo_user.country
     *
     * @return the value of demo_user.country
     *
     * @abatorgenerated Fri Oct 13 15:16:02 PDT 2006
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column demo_user.country
     *
     * @param country the value for demo_user.country
     *
     * @abatorgenerated Fri Oct 13 15:16:02 PDT 2006
     */
    public void setCountry(String country) {
        if(country != null && !country.isEmpty()) {
            this.country = country;
        }
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column demo_user.phone
     *
     * @return the value of demo_user.phone
     *
     * @abatorgenerated Fri Oct 13 15:16:02 PDT 2006
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column demo_user.phone
     *
     * @param phone the value for demo_user.phone
     *
     * @abatorgenerated Fri Oct 13 15:16:02 PDT 2006
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column demo_user.email
     *
     * @return the value of demo_user.email
     *
     * @abatorgenerated Fri Oct 13 15:16:02 PDT 2006
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column demo_user.email
     *
     * @param email the value for demo_user.email
     *
     * @abatorgenerated Fri Oct 13 15:16:02 PDT 2006
     */
    public void setEmail(String email) {
        this.email = email;
    }


    // T&C acceptance date
    private Date acceptDate;

	public Date getAcceptDate() {
		return acceptDate;
	}

	public void setAcceptDate(Date acceptDate) {
		this.acceptDate = acceptDate;
	}

    public void setStateNull(){
        this.state=null;
    }

    public boolean isUpdateBalance() {
        return updateBalance;
    }

    public void setUpdateBalance(final boolean updateBalance) {
        this.updateBalance = updateBalance;
    }
}