package com.b2s.db.model;

public class DemoUserKey implements java.io.Serializable{
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column demo_user.programid
     *
     * @abatorgenerated Fri Oct 13 15:16:02 PDT 2006
     */
    private String programid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column demo_user.userid
     *
     * @abatorgenerated Fri Oct 13 15:16:02 PDT 2006
     */
    private String userid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column demo_user.varid
     *
     * @abatorgenerated Fri Oct 13 15:16:02 PDT 2006
     */
    private String varid;
    
    private String password;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column demo_user.programid
     *
     * @return the value of demo_user.programid
     *
     * @abatorgenerated Fri Oct 13 15:16:02 PDT 2006
     */
    public String getProgramid() {
        return programid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column demo_user.programid
     *
     * @param programid the value for demo_user.programid
     *
     * @abatorgenerated Fri Oct 13 15:16:02 PDT 2006
     */
    public void setProgramid(String programid) {
        this.programid = programid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column demo_user.userid
     *
     * @return the value of demo_user.userid
     *
     * @abatorgenerated Fri Oct 13 15:16:02 PDT 2006
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column demo_user.userid
     *
     * @param userid the value for demo_user.userid
     *
     * @abatorgenerated Fri Oct 13 15:16:02 PDT 2006
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column demo_user.varid
     *
     * @return the value of demo_user.varid
     *
     * @abatorgenerated Fri Oct 13 15:16:02 PDT 2006
     */
    public String getVarid() {
        return varid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column demo_user.varid
     *
     * @param varid the value for demo_user.varid
     *
     * @abatorgenerated Fri Oct 13 15:16:02 PDT 2006
     */
    public void setVarid(String varid) {
        this.varid = varid;
    }
    
       public void setPassword(String password) {
        this.password = password;
    }
    
    public String getPassword() {
    	return password;
    }
    
}