package com.b2s.db.model;

import com.b2s.rewards.common.util.CommonConstants;
import com.b2s.shop.common.order.OrderLineIF;
import com.b2s.rewards.model.Store;
import com.b2s.service.model.Merchant;
import org.apache.commons.lang.StringUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.Date;
import java.util.List;

@SuppressWarnings("OverlyComplexClass")
public class OrderLine extends OrderLineKey implements OrderLineIF {
    private static final Logger LOGGER = LoggerFactory.getLogger(OrderLine.class);

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_line.supplier_id
     *
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    private String supplierId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_line.var_id
     *
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    private String varId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_line.program_id
     *
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    private String programId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_line.category
     *
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    private String category;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_line.supplier_order_id
     *
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    private String supplierOrderId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_line.item_id
     *
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    private String itemId;
    protected boolean isQuantityUsed = true;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_line.name
     *
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    private String name;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_line.image_url
     *
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    private String imageUrl;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_line.color
     *
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    private String color;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_line.weight
     *
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    private Integer weight;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_line.size
     *
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    private String size;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_line.attr1
     *
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    private String attr1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_line.attr2
     *
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    private String attr2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_line.attr3
     *
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    private String attr3;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_line.is_eligible_for_super_saver_shipping
     *
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    private String isEligibleForSuperSaverShipping;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_line.quantity
     *
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    private Integer quantity;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_line.supplier_item_price
     *
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    private Integer supplierItemPrice;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_line.supplier_tax_price
     *
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    private Integer supplierTaxPrice;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_line.b2s_tax_price
     *
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    private Integer b2sTaxPrice;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_line.supplier_per_shipment_price
     *
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    private Integer supplierPerShipmentPrice;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_line.supplier_shipping_unit
     *
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    private String supplierShippingUnit;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_line.supplier_shipping_unit_price
     *
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    private Integer supplierShippingUnitPrice;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_line.supplier_single_item_shipping_price
     *
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    private Integer supplierSingleItemShippingPrice;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_line.supplier_shipping_price
     *
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    private Integer supplierShippingPrice;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_line.conv_rate
     *
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    private Double convRate;

    private Double effConvRate;

    private Integer pointsRoundingIncrement;


    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_line.tax_rate
     *
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    private Integer taxRate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_line.b2s_tax_rate
     *
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    private Integer b2sTaxRate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_line.b2s_item_margin
     *
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    private Double b2sItemMargin;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_line.var_item_margin
     *
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    private Double varItemMargin;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_line.b2s_shipping_margin
     *
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    private Double b2sShippingMargin;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_line.var_shipping_margin
     *
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    private Double varShippingMargin;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_line.item_points
     *
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    private Double itemPoints;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_line.tax_points
     *
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    private Double taxPoints;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_line.b2s_tax_points
     *
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    private Double b2sTaxPoints;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_line.shipping_points
     *
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    private Double shippingPoints;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_line.order_line_points
     *
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    private Integer orderLinePoints;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_line.b2s_item_profit_price
     *
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    private Integer b2sItemProfitPrice;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_line.b2s_tax_profit_price
     *
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    private Integer b2sTaxProfitPrice;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_line.b2s_shipping_profit_price
     *
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    private Integer b2sShippingProfitPrice;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_line.var_item_profit_price
     *
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    private Integer varItemProfitPrice;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_line.var_tax_profit_price
     *
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    private Integer varTaxProfitPrice;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_line.var_shipping_profit_price
     *
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    private Integer varShippingProfitPrice;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_line.var_order_line_price
     *
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    private Integer varOrderLinePrice;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_line.comment
     *
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    private String comment;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_line.create_date
     *
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    private Date createDate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_line.order_status
     *
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    private Integer orderStatus;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_line.order_line_type
     *
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    private String orderLineType;

    /**
     * order source
     * @since b2r-rewardstep 5.2
     */
    private String orderSource;
    
    
    /**
     * Refer to order_line_ref_policy.id 
     *
     * ID is a md5 checksum of policy
     */
    private String policyId;
    
    
    @SuppressWarnings("TransientFieldInNonSerializableClass")
    private transient String policy;
    
    /**
     * SYMPRJ-932
     */
    private Date travelStartDate;
    
    /**
     * SYMPRJ-938
     */
    private Date travelEndDate;
    
    /**
     * TODO, Move to orderlineAdditionalInfo or create a  table??
     * SYMPRJ-938,  For billing report .
     */
    private Integer bookingQuantity;
    
    /**
     * SYMPRJ-930
     */
    private Integer b2sOnlineFee;
    
    /**
     * SYMPRJ-930
     */
    private Integer b2sOfflineFee;
    
    /*
     * SYMPRJ-1199
     */
    private Integer orderLineUndiscountedUnitFee;

    private Long notificationId;

    /**
     * This represents the list of taxes for this order line.  The key is the name of the tax and the value is
     * a Tax model object.  An example tax is state sales tax.
     */
    private List<OrderLineTax> taxes;

    /**
     * This represents the list of fees for this order line.  The key is the name of the fee and the value is
     * a Fee model object.  An example fee is Best Buy's environment handling fee.
     */
    private List<OrderLineFee> fees;

    private BigDecimal cashBuyInPoints;

    private BigDecimal cashBuyInPrice;
    
    private String gatewayOrderNumber;

    List<OrderLineAttribute> orderLineAttributes;

    private Double fxRate;

    private Long productGroupId;

    private Integer paymentDuration;

    private Double payrollAmount;
    private Double payrollTotalAmount;

    private String paymentFrequency;

    private Integer discountedSupplierItemPrice;
    private Integer discountedVarOrderLinePrice;
    private Integer discountedFees;
    private Integer discountedTaxes;
    private String bundleId;

    public Double getPayrollTotalAmount() {
        return payrollTotalAmount;
    }

    public void setPayrollTotalAmount(final Double payrollTotalAmount) {
        this.payrollTotalAmount = payrollTotalAmount;
    }

    public Double getFxRate() {
        return fxRate;
    }

    public void setFxRate(final Double fxRate) {
        this.fxRate = fxRate;
    }

    public Long getProductGroupId() {
        return productGroupId;
    }

    public void setProductGroupId(Long productGroupId) {
        this.productGroupId = productGroupId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_line.supplier_id
     *
     * @return the value of order_line.supplier_id
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public String getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_line.supplier_id
     *
     * @param supplierId the value for order_line.supplier_id
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public void setSupplierId(final String supplierId) {
        this.supplierId = supplierId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_line.var_id
     *
     * @return the value of order_line.var_id
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public String getVarId() {
        return varId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_line.var_id
     *
     * @param varId the value for order_line.var_id
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public void setVarId(final String varId) {
        this.varId = varId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_line.program_id
     *
     * @return the value of order_line.program_id
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public String getProgramId() {
        return programId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_line.program_id
     *
     * @param programId the value for order_line.program_id
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public void setProgramId(final String programId) {
        this.programId = programId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_line.category
     *
     * @return the value of order_line.category
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_line.category
     *
     * @param category the value for order_line.category
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public void setCategory(final String category) {
        this.category = category;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_line.supplier_order_id
     *
     * @return the value of order_line.supplier_order_id
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public String getSupplierOrderId() {
        return supplierOrderId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_line.supplier_order_id
     *
     * @param supplierOrderId the value for order_line.supplier_order_id
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public void setSupplierOrderId(final String supplierOrderId) {
        this.supplierOrderId = supplierOrderId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_line.item_id
     *
     * @return the value of order_line.item_id
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public String getItemId() {
        return itemId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_line.item_id
     *
     * @param itemId the value for order_line.item_id
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public void setItemId(final String itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_line.name
     *
     * @return the value of order_line.name
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_line.name
     *
     * @param name the value for order_line.name
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public void setName(final String name) {
        this.name = name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_line.image_url
     *
     * @return the value of order_line.image_url
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_line.image_url
     *
     * @param imageUrl the value for order_line.image_url
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public void setImageUrl(final String imageUrl) {
        this.imageUrl = imageUrl;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_line.color
     *
     * @return the value of order_line.color
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_line.color
     *
     * @param color the value for order_line.color
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public void setColor(final String color) {
        this.color = color;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_line.weight
     *
     * @return the value of order_line.weight
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_line.weight
     *
     * @param weight the value for order_line.weight
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public void setWeight(final Integer weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_line.size
     *
     * @return the value of order_line.size
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_line.size
     *
     * @param size the value for order_line.size
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public void setSize(final String size) {
        this.size = size;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_line.attr1
     *
     * @return the value of order_line.attr1
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public String getAttr1() {
        return attr1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_line.attr1
     *
     * @param attr1 the value for order_line.attr1
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public void setAttr1(final String attr1) {
        this.attr1 = attr1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_line.attr2
     *
     * @return the value of order_line.attr2
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public String getAttr2() {
        return attr2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_line.attr2
     *
     * @param attr2 the value for order_line.attr2
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public void setAttr2(final String attr2) {
        this.attr2 = attr2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_line.attr3
     *
     * @return the value of order_line.attr3
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public String getAttr3() {
        return attr3;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_line.attr3
     *
     * @param attr3 the value for order_line.attr3
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public void setAttr3(final String attr3) {
        this.attr3 = attr3;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_line.is_eligible_for_super_saver_shipping
     *
     * @return the value of order_line.is_eligible_for_super_saver_shipping
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public String getIsEligibleForSuperSaverShipping() {
        return isEligibleForSuperSaverShipping;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_line.is_eligible_for_super_saver_shipping
     *
     * @param isEligibleForSuperSaverShipping
     *         the value for order_line.is_eligible_for_super_saver_shipping
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public void setIsEligibleForSuperSaverShipping(final String isEligibleForSuperSaverShipping) {
        this.isEligibleForSuperSaverShipping = isEligibleForSuperSaverShipping;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_line.quantity
     *
     * @return the value of order_line.quantity
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_line.quantity
     *
     * @param quantity the value for order_line.quantity
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public void setQuantity(final Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_line.supplier_item_price
     *
     * @return the value of order_line.supplier_item_price
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public Integer getSupplierItemPrice() {
        return supplierItemPrice;
    }

    public Integer getDisplayItemPrice(){
        return supplierItemPrice + supplierTaxPrice;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_line.supplier_item_price
     *
     * @param supplierItemPrice the value for order_line.supplier_item_price
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public void setSupplierItemPrice(final Integer supplierItemPrice) {
        this.supplierItemPrice = supplierItemPrice;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_line.supplier_tax_price
     *
     * @return the value of order_line.supplier_tax_price
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public Integer getSupplierTaxPrice() {
        return supplierTaxPrice;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_line.supplier_tax_price
     *
     * @param supplierTaxPrice the value for order_line.supplier_tax_price
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public void setSupplierTaxPrice(final Integer supplierTaxPrice) {
        this.supplierTaxPrice = supplierTaxPrice;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_line.b2s_tax_price
     *
     * @return the value of order_line.b2s_tax_price
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public Integer getB2sTaxPrice() {
        return b2sTaxPrice;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_line.b2s_tax_price
     *
     * @param b2sTaxPrice the value for order_line.b2s_tax_price
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public void setB2sTaxPrice(final Integer b2sTaxPrice) {
        this.b2sTaxPrice = b2sTaxPrice;
    }


    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_line.supplier_per_shipment_price
     *
     * @return the value of order_line.supplier_per_shipment_price
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public Integer getSupplierPerShipmentPrice() {
        return supplierPerShipmentPrice;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_line.supplier_per_shipment_price
     *
     * @param supplierPerShipmentPrice the value for order_line.supplier_per_shipment_price
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public void setSupplierPerShipmentPrice(final Integer supplierPerShipmentPrice) {
        this.supplierPerShipmentPrice = supplierPerShipmentPrice;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_line.supplier_shipping_unit
     *
     * @return the value of order_line.supplier_shipping_unit
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public String getSupplierShippingUnit() {
        return supplierShippingUnit;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_line.supplier_shipping_unit
     *
     * @param supplierShippingUnit the value for order_line.supplier_shipping_unit
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public void setSupplierShippingUnit(final String supplierShippingUnit) {
        this.supplierShippingUnit = supplierShippingUnit;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_line.supplier_shipping_unit_price
     *
     * @return the value of order_line.supplier_shipping_unit_price
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public Integer getSupplierShippingUnitPrice() {
        return supplierShippingUnitPrice;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_line.supplier_shipping_unit_price
     *
     * @param supplierShippingUnitPrice the value for order_line.supplier_shipping_unit_price
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public void setSupplierShippingUnitPrice(final Integer supplierShippingUnitPrice) {
        this.supplierShippingUnitPrice = supplierShippingUnitPrice;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_line.supplier_single_item_shipping_price
     *
     * @return the value of order_line.supplier_single_item_shipping_price
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public Integer getSupplierSingleItemShippingPrice() {
        return supplierSingleItemShippingPrice;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_line.supplier_single_item_shipping_price
     *
     * @param supplierSingleItemShippingPrice
     *         the value for order_line.supplier_single_item_shipping_price
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public void setSupplierSingleItemShippingPrice(final Integer supplierSingleItemShippingPrice) {
        this.supplierSingleItemShippingPrice = supplierSingleItemShippingPrice;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_line.supplier_shipping_price
     *
     * @return the value of order_line.supplier_shipping_price
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public Integer getSupplierShippingPrice() {
        return supplierShippingPrice;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_line.supplier_shipping_price
     *
     * @param supplierShippingPrice the value for order_line.supplier_shipping_price
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public void setSupplierShippingPrice(final Integer supplierShippingPrice) {
        this.supplierShippingPrice = supplierShippingPrice;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_line.conv_rate
     *
     * @return the value of order_line.conv_rate
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public Double getConvRate() {
        return convRate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_line.conv_rate
     *
     * @param convRate the value for order_line.conv_rate
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public void setConvRate(final Double convRate) {
        this.convRate = convRate;
    }

    public Double getEffConvRate() {
        return effConvRate;
    }

    public void setEffConvRate(Double effConvRate) {
        this.effConvRate = effConvRate;
    }

    public Integer getPointsRoundingIncrement() {
        return pointsRoundingIncrement;
    }

    public void setPointsRoundingIncrement(Integer pointsRoundingIncrement) {
        this.pointsRoundingIncrement = pointsRoundingIncrement;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_line.tax_rate
     *
     * @return the value of order_line.tax_rate
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public Integer getTaxRate() {
        return taxRate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_line.tax_rate
     *
     * @param taxRate the value for order_line.tax_rate
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public void setTaxRate(final Integer taxRate) {
        this.taxRate = taxRate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_line.b2s_tax_rate
     *
     * @return the value of order_line.b2s_tax_rate
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public Integer getB2sTaxRate() {
        return b2sTaxRate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_line.b2s_tax_rate
     *
     * @param b2sTaxRate the value for order_line.b2s_tax_rate
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public void setB2sTaxRate(final Integer b2sTaxRate) {
        this.b2sTaxRate = b2sTaxRate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_line.b2s_item_margin
     *
     * @return the value of order_line.b2s_item_margin
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public Double getB2sItemMargin() {
        return b2sItemMargin;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_line.b2s_item_margin
     *
     * @param b2sItemMargin the value for order_line.b2s_item_margin
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public void setB2sItemMargin(final Double b2sItemMargin) {
        this.b2sItemMargin = b2sItemMargin;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_line.var_item_margin
     *
     * @return the value of order_line.var_item_margin
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public Double getVarItemMargin() {
        return varItemMargin;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_line.var_item_margin
     *
     * @param varItemMargin the value for order_line.var_item_margin
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public void setVarItemMargin(final Double varItemMargin) {
        this.varItemMargin = varItemMargin;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_line.b2s_shipping_margin
     *
     * @return the value of order_line.b2s_shipping_margin
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public Double getB2sShippingMargin() {
        return b2sShippingMargin;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_line.b2s_shipping_margin
     *
     * @param b2sShippingMargin the value for order_line.b2s_shipping_margin
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public void setB2sShippingMargin(final Double b2sShippingMargin) {
        this.b2sShippingMargin = b2sShippingMargin;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_line.var_shipping_margin
     *
     * @return the value of order_line.var_shipping_margin
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public Double getVarShippingMargin() {
        return varShippingMargin;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_line.var_shipping_margin
     *
     * @param varShippingMargin the value for order_line.var_shipping_margin
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public void setVarShippingMargin(final Double varShippingMargin) {
        this.varShippingMargin = varShippingMargin;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_line.item_points
     *
     * @return the value of order_line.item_points
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public Double getItemPoints() {
        return itemPoints;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_line.item_points
     *
     * @param itemPoints the value for order_line.item_points
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public void setItemPoints(final Double itemPoints) {
        this.itemPoints = itemPoints;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_line.tax_points
     *
     * @return the value of order_line.tax_points
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public Double getTaxPoints() {
        return taxPoints;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_line.tax_points
     *
     * @param taxPoints the value for order_line.tax_points
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public void setTaxPoints(final Double taxPoints) {
        this.taxPoints = taxPoints;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_line.b2s_tax_points
     *
     * @return the value of order_line.b2s_tax_points
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public Double getB2sTaxPoints() {
        return b2sTaxPoints;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_line.b2s_tax_points
     *
     * @param b2sTaxPoints the value for order_line.b2s_tax_points
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public void setB2sTaxPoints(final Double b2sTaxPoints) {
        this.b2sTaxPoints = b2sTaxPoints;
    }


    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_line.shipping_points
     *
     * @return the value of order_line.shipping_points
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public Double getShippingPoints() {
        return shippingPoints;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_line.shipping_points
     *
     * @param shippingPoints the value for order_line.shipping_points
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public void setShippingPoints(final Double shippingPoints) {
        this.shippingPoints = shippingPoints;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_line.order_line_points
     *
     * @return the value of order_line.order_line_points
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public Integer getOrderLinePoints() {
        return orderLinePoints;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_line.order_line_points
     *
     * @param orderLinePoints the value for order_line.order_line_points
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public void setOrderLinePoints(final Integer orderLinePoints) {
        this.orderLinePoints = orderLinePoints;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_line.b2s_item_profit_price
     *
     * @return the value of order_line.b2s_item_profit_price
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public Integer getB2sItemProfitPrice() {
        return b2sItemProfitPrice;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_line.b2s_item_profit_price
     *
     * @param b2sItemProfitPrice the value for order_line.b2s_item_profit_price
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public void setB2sItemProfitPrice(final Integer b2sItemProfitPrice) {
        this.b2sItemProfitPrice = b2sItemProfitPrice;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_line.b2s_tax_profit_price
     *
     * @return the value of order_line.b2s_tax_profit_price
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public Integer getB2sTaxProfitPrice() {
        return b2sTaxProfitPrice;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_line.b2s_tax_profit_price
     *
     * @param b2sTaxProfitPrice the value for order_line.b2s_tax_profit_price
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public void setB2sTaxProfitPrice(final Integer b2sTaxProfitPrice) {
        this.b2sTaxProfitPrice = b2sTaxProfitPrice;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_line.b2s_shipping_profit_price
     *
     * @return the value of order_line.b2s_shipping_profit_price
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public Integer getB2sShippingProfitPrice() {
        return b2sShippingProfitPrice;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_line.b2s_shipping_profit_price
     *
     * @param b2sShippingProfitPrice the value for order_line.b2s_shipping_profit_price
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public void setB2sShippingProfitPrice(final Integer b2sShippingProfitPrice) {
        this.b2sShippingProfitPrice = b2sShippingProfitPrice;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_line.var_item_profit_price
     *
     * @return the value of order_line.var_item_profit_price
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public Integer getVarItemProfitPrice() {
        return varItemProfitPrice;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_line.var_item_profit_price
     *
     * @param varItemProfitPrice the value for order_line.var_item_profit_price
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public void setVarItemProfitPrice(final Integer varItemProfitPrice) {
        this.varItemProfitPrice = varItemProfitPrice;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_line.var_tax_profit_price
     *
     * @return the value of order_line.var_tax_profit_price
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public Integer getVarTaxProfitPrice() {
        return varTaxProfitPrice;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_line.var_tax_profit_price
     *
     * @param varTaxProfitPrice the value for order_line.var_tax_profit_price
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public void setVarTaxProfitPrice(final Integer varTaxProfitPrice) {
        this.varTaxProfitPrice = varTaxProfitPrice;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_line.var_shipping_profit_price
     *
     * @return the value of order_line.var_shipping_profit_price
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public Integer getVarShippingProfitPrice() {
        return varShippingProfitPrice;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_line.var_shipping_profit_price
     *
     * @param varShippingProfitPrice the value for order_line.var_shipping_profit_price
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public void setVarShippingProfitPrice(final Integer varShippingProfitPrice) {
        this.varShippingProfitPrice = varShippingProfitPrice;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_line.var_order_line_price
     *
     * @return the value of order_line.var_order_line_price
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public Integer getVarOrderLinePrice() {
        return varOrderLinePrice;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_line.var_order_line_price
     *
     * @param varOrderLinePrice the value for order_line.var_order_line_price
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public void setVarOrderLinePrice(final Integer varOrderLinePrice) {
        this.varOrderLinePrice = varOrderLinePrice;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_line.comment
     *
     * @return the value of order_line.comment
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_line.comment
     *
     * @param comment the value for order_line.comment
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public void setComment(final String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_line.create_date
     *
     * @return the value of order_line.create_date
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_line.create_date
     *
     * @param createDate the value for order_line.create_date
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @SuppressWarnings("AssignmentToDateFieldFromParameter")
    @Override
    public void setCreateDate(final Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_line.order_status
     *
     * @return the value of order_line.order_status
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public Integer getOrderStatus() {
        return orderStatus;
    }

    @Override
    public void setOrderStatus(final Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    @SuppressWarnings("BooleanMethodNameMustStartWithQuestion")
    public boolean getIsQuantityUsed() {
        return isQuantityUsed;
    }

    public void setIsQuantityUsed(final boolean isQuantityUsed) {
        this.isQuantityUsed = isQuantityUsed;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_line.order_line_type
     *
     * @return the value of order_line.order_line_type
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public String getOrderLineType() {
        return orderLineType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_line.order_line_type
     *
     * @param orderLineType the value for order_line.order_line_type
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    @Override
    public void setOrderLineType(final String orderLineType) {
        this.orderLineType = orderLineType;
    }

    public BigDecimal getCashBuyInPoints() {
        return cashBuyInPoints;
    }

    public void setCashBuyInPoints(final BigDecimal cashBuyInPoints) {
        this.cashBuyInPoints = cashBuyInPoints;
    }

    public BigDecimal getCashBuyInPrice() {
        return cashBuyInPrice;
    }

    public void setCashBuyInPrice(final BigDecimal cashBuyInPrice) {
        this.cashBuyInPrice = cashBuyInPrice;
    }

    // itemPriceOriginal stores the item price in original currency.
    // It is created for Amazon UK, etc. implementation.
    private Integer itemPriceOriginal = 0;

    @Override
    public Integer getItemPriceOriginal() {
        return itemPriceOriginal;
    }

    @Override
    public void setItemPriceOriginal(final int itemPriceOriginal) {
        this.itemPriceOriginal = itemPriceOriginal;
    }

    private String brand;
    private String manufacturer;
    private String upc;
    private String categoryPath;
    private String merchantId;
    private String sku;
    private String shippingMethod;
    private String sellerId;
    private String listingId;
    private String storeId;
    private Store store;
    private String orderDelay;
    private String appleSku;

    public String getAppleSku() {
        return appleSku;
    }

    public OrderLine setAppleSku(String appleSku) {
        this.appleSku = appleSku;
        return this;
    }

    public String getOrderDelay() {
        return orderDelay;
    }

    public void setOrderDelay(final String orderDelay) {
        this.orderDelay = orderDelay;
    }

    public String getBrand() {
        return brand;
    }

    public void setBrand(final String brand) {
        this.brand = brand;
    }

    public String getManufacturer() {
        return manufacturer;
    }

    public void setManufacturer(final String manufacturer) {
        this.manufacturer = manufacturer;
    }

    public String getUpc() {
        return upc;
    }

    public void setUpc(final String upc) {
        this.upc = upc;
    }

    public String getCategoryPath() {
        return categoryPath;
    }

    public void setCategoryPath(final String categoryPath) {
        this.categoryPath = categoryPath;
    }

    public String getMerchantId() {
        if (this.merchantId == null || this.merchantId.trim().isEmpty()) {
            this.merchantId = this.supplierId;
        }
        return merchantId;
    }

    public void setMerchantId(final String merchantId) {
        this.merchantId = merchantId;
    }

    public String getSku() {
        return sku;
    }

    public void setSku(final String sku) {
        this.sku = sku;
    }

    public String getShippingMethod() {
        return shippingMethod;
    }

    public void setShippingMethod(final String shippingMethod) {
        this.shippingMethod = shippingMethod;
    }

    public String getSellerId() {
        return sellerId;
    }

    public void setSellerId(final String sellerId) {
        this.sellerId = sellerId;
    }

    public String getListingId() {
        return listingId;
    }

    public void setListingId(final String listingId) {
        this.listingId = listingId;
    }

    public String getStoreId() {
        return storeId;
    }

    public void setStoreId(final String storeId) {
        this.storeId = storeId;
    }

    public Store getStore() {
        return store;
    }

    public void setStore(final Store store) {
        this.store = store;
    }

    public String getMerchantName() {
        String merchantName = "";
        try {
            // Locate the merchant id in the enum
            final Merchant enumMerchant = Merchant.forCode(Integer.parseInt(this.getMerchantId()));
            if( null == enumMerchant ) {
                // If, by some chance, the enum is out of sync or we have a merchantId incorrectly associated with
                // the line, then warn about this
                LOGGER.warn("Merchant ID {} could not be resolved",this.getMerchantId());
            } else {
                merchantName = enumMerchant.getFullName();
            }
        } catch (final NumberFormatException e) {
            LOGGER.error("Error parsing merchant ID for getting merchant name", e);
        }
        return merchantName;
    }

    public String getOrderSource() {
        return orderSource;
    }

    public void setOrderSource(final String orderSource) {
        this.orderSource = orderSource;
    }
    public String getPolicyId() {
        return policyId;
    }

    public void setPolicyId(final String policyId) {
        this.policyId = policyId;
    }

    public String getPolicy() {
        return policy;
    }

    public void setPolicy(final String policy) {
        this.policy = policy;
    }

    public Date getTravelStartDate() {
        return travelStartDate;
    }

    @SuppressWarnings("AssignmentToDateFieldFromParameter")
    public void setTravelStartDate(final Date travelStartDate) {
        this.travelStartDate = travelStartDate;
    }

    public Integer getB2sOnlineFee() {
        return b2sOnlineFee;
    }

    public void setB2sOnlineFee(final Integer b2sOnlineFee) {
        this.b2sOnlineFee = b2sOnlineFee;
    }

    public Integer getB2sOfflineFee() {
        return b2sOfflineFee;
    }

    public void setB2sOfflineFee(final Integer b2sOfflineFee) {
        this.b2sOfflineFee = b2sOfflineFee;
    }
    
    public Integer getOrderLineUndiscountedUnitFee() {
        return orderLineUndiscountedUnitFee;
    }

    public void setOrderLineUndiscountedUnitFee(final Integer orderLineUndiscountedUnitFee) {
        this.orderLineUndiscountedUnitFee = orderLineUndiscountedUnitFee;
    }
    
    public Date getTravelEndDate() {
        return travelEndDate;
    }

    @SuppressWarnings("AssignmentToDateFieldFromParameter")
    public void setTravelEndDate(final Date travelEndDate) {
        this.travelEndDate = travelEndDate;
    }

    public Integer getBookingQuantity() {
        return bookingQuantity;
    }

    public void setBookingQuantity(final Integer bookingQuantity) {
        this.bookingQuantity = bookingQuantity;
    }

    public List<OrderLineTax> getTaxes() {
        return taxes;
    }

    public void setTaxes(final List<OrderLineTax> taxes) {
        this.taxes = taxes;
    }

    public Long getNotificationId() {
        return notificationId;
    }
    public void setNotificationId(final Long notificationId) {
        this.notificationId = notificationId;
    }

    /*
     *  This method calculates the total tax points for this orderline for 1 quantity of this item.  This value is
     *  not persisted in the database, but calculated based on other values stored in the database.  The formula for
     *  the calculation is the following:
     *
     *  Total Tax Points = sum of all itemized taxes in points for this order line in the ORDER_LINE_TAX table
     */
    public Integer getTotalTaxesInPoints() {
        Integer total = 0;
        if (taxes!=null) {
            for (final OrderLineTax lineTax : taxes) {
                total += lineTax.getPoints();
            }
        }
        return total;
    }

    /*
     *  This method calculates the total tax price in pennies for this orderline for 1 quantity of this item.  This
     *  value is not persisted in the database, but calculated based on other values stored in the database.  The
     *  formula for the calculation is the following:
     *
     *  Total Tax Money = sum of all itemized taxes in money for this order line in the ORDER_LINE_TAX table
     */
    public BigDecimal getTotalTaxesInMoneyMinor() {
        BigDecimal total = BigDecimal.ZERO;
        if (taxes != null) {
            for (final OrderLineTax lineTax : taxes) {
                total = total.add(lineTax.getAmount());
            }
        }
        return total;
    }

    public BigDecimal getDiscountedTotalTaxesInMoneyMinor(){
        return BigDecimal.valueOf(this.discountedTaxes)
                .divide(new BigDecimal(CommonConstants.CENTS_TO_DOLLARS_DIVISOR))
                .setScale(2,RoundingMode.HALF_UP);
    }

    public List<OrderLineFee> getFees() {
        return fees;
    }

    public void setFees(final List<OrderLineFee> fees) {
        this.fees = fees;
    }
    
    
    
    public String getGatewayOrderNumber() {
		return gatewayOrderNumber;
	}

	public void setGatewayOrderNumber(String gatewayOrderNumber) {
		this.gatewayOrderNumber = gatewayOrderNumber;
	}

	/*
     *  This method calculates the total fee points for this orderline for 1 quantity of this item.  This value is
     *  not persisted in the database, but calculated based on other values stored in the database.  The formula for
     *  the calculation is the following:
     *
     *  Total Fee Points = sum of all itemized fees in points for this order line in the ORDER_LINE_FEE table
     */
    public Integer getTotalFeesInPoints() {
        Integer total = 0;
        if (fees!=null) {
            for (final OrderLineFee lineFee : fees) {
                total += lineFee.getPoints();
            }
        }
        return total;
    }

    /*
     *  This method calculates the total fee price in pennies for this orderline for 1 quantity of this item.  This
     *  value is not persisted in the database, but calculated based on other values stored in the database.  The
     *  formula for the calculation is the following:
     *
     *  Total Fee Money = sum of all itemized fees in money for this order line in the ORDER_LINE_FEE table
     */
    public BigDecimal getTotalFeesInMoneyMinor() {
        BigDecimal total = BigDecimal.ZERO;
        if (fees != null) {
            for(final OrderLineFee lineFee : fees) {
                total = total.add(lineFee.getAmount());
            }
        }
        return total;
    }

    public BigDecimal getDiscountedTotalFeesInMoneyMinor(){
        return BigDecimal.valueOf(this.discountedFees)
            .divide(new BigDecimal(CommonConstants.CENTS_TO_DOLLARS_DIVISOR))
            .setScale(2,RoundingMode.HALF_UP);
    }

    /*
     *  This method calculates the total supplier price in pennies for this orderline for 1 quantity of this item.  This
     *  value is not persisted in the database, but calculated based on other values stored in the database.  The
     *  formula for the calculation is the following:
     *
     *  Total supplier price = supplier_item_price + supplier_shipping_price + total taxes + total fees
     */
    public BigDecimal getSupplierTotalInMoneyMinor() {
        BigDecimal total = BigDecimal.ZERO;
        if(StringUtils.equals(this.attr1,CommonConstants.DISCOUNT_APPLIED)){
            total = total.add(BigDecimal.valueOf(this.discountedSupplierItemPrice));
            total = total.add(BigDecimal.valueOf(this.discountedTaxes));
            total = total.add(BigDecimal.valueOf(this.discountedFees));
        }else{
            total = total.add(BigDecimal.valueOf(this.supplierItemPrice));
            total = total.add(this.getTotalTaxesInMoneyMinor().multiply(new BigDecimal(100)));
            total = total.add(this.getTotalFeesInMoneyMinor().multiply(new BigDecimal(100)));
        }
        total = total.add(BigDecimal.valueOf(this.supplierShippingPrice));
        return total;
    }

    /*
     *  This method calculates the total supplier price in pennies for this orderline for 1 quantity of this item.  This
     *  value is not persisted in the database, but calculated based on other values stored in the database.  The
     *  formula for the calculation is the following:
     *
     *  Total supplier price = supplier_item_price + supplier_shipping_price + total taxes + total fees
    */
    public BigDecimal getSupplierTotalWithSupplierTaxInMoneyMinor() {
        BigDecimal total = BigDecimal.ZERO;
        if(StringUtils.equals(this.attr1,CommonConstants.DISCOUNT_APPLIED)){
            total = total.add(BigDecimal.valueOf(this.discountedSupplierItemPrice));
            total = total.add(BigDecimal.valueOf(this.discountedTaxes));
            total = total.add(BigDecimal.valueOf(this.discountedFees));
        }else{
            total = total.add(BigDecimal.valueOf(this.supplierItemPrice));
            total = total.add(BigDecimal.valueOf(this.supplierTaxPrice));
            total = total.add(this.getTotalFeesInMoneyMinor().multiply(new BigDecimal(100)));
        }
        total = total.add(BigDecimal.valueOf(this.supplierShippingPrice));
        return total;
    }

    public List<OrderLineAttribute> getOrderAttributes() {
        return orderLineAttributes;
    }

    public void setOrderAttributes(final List<OrderLineAttribute> orderLineAttributes) {
        this.orderLineAttributes = orderLineAttributes;
    }

    public Integer getPaymentDuration() {
        return paymentDuration;
    }

    public void setPaymentDuration(final Integer paymentDuration) {
        this.paymentDuration = paymentDuration;
    }

    public Double getPayrollAmount() {
        return payrollAmount;
    }

    public void setPayrollAmount(final Double payrollAmount) {
        this.payrollAmount = payrollAmount;
    }

    public String getPaymentFrequency() {
        return paymentFrequency;
    }

    public void setPaymentFrequency(final String paymentFrequency) {
        this.paymentFrequency = paymentFrequency;
    }

    public Integer getDiscountedSupplierItemPrice() {
        return discountedSupplierItemPrice;
    }

    public void setDiscountedSupplierItemPrice(final Integer discountedSupplierItemPrice) {
        this.discountedSupplierItemPrice = discountedSupplierItemPrice;
    }

    public Integer getDiscountedVarOrderLinePrice() {
        return discountedVarOrderLinePrice;
    }

    public void setDiscountedVarOrderLinePrice(final Integer discountedVarOrderLinePrice) {
        this.discountedVarOrderLinePrice = discountedVarOrderLinePrice;
    }

    public Integer getDiscountedFees() {
        return discountedFees;
    }

    public void setDiscountedFees(final Integer discountedFees) {
        this.discountedFees = discountedFees;
    }

    public Integer getDiscountedTaxes() {
        return discountedTaxes;
    }

    public void setDiscountedTaxes(final Integer discountedTaxes) {
        this.discountedTaxes = discountedTaxes;
    }

    public String getBundleId() {
        return bundleId;
    }

    public void setBundleId(String bundleId) {
        this.bundleId = bundleId;
    }

    @Override
    public String toString() {
        return "OrderLine{" +
                "supplierId='" + supplierId + '\'' +
                ", varId='" + varId + '\'' +
                ", programId='" + programId + '\'' +
                ", category='" + category + '\'' +
                ", supplierOrderId='" + supplierOrderId + '\'' +
                ", itemId='" + itemId + '\'' +
                ", isQuantityUsed=" + isQuantityUsed +
                ", name='" + name + '\'' +
                ", imageUrl='" + imageUrl + '\'' +
                ", color='" + color + '\'' +
                ", weight=" + weight +
                ", size='" + size + '\'' +
                ", attr1='" + attr1 + '\'' +
                ", attr2='" + attr2 + '\'' +
                ", attr3='" + attr3 + '\'' +
                ", isEligibleForSuperSaverShipping='" + isEligibleForSuperSaverShipping + '\'' +
                ", quantity=" + quantity +
                ", supplierItemPrice=" + supplierItemPrice +
                ", supplierTaxPrice=" + supplierTaxPrice +
                ", b2sTaxPrice=" + b2sTaxPrice +
                ", supplierPerShipmentPrice=" + supplierPerShipmentPrice +
                ", supplierShippingUnit='" + supplierShippingUnit + '\'' +
                ", supplierShippingUnitPrice=" + supplierShippingUnitPrice +
                ", supplierSingleItemShippingPrice=" + supplierSingleItemShippingPrice +
                ", supplierShippingPrice=" + supplierShippingPrice +
                ", convRate=" + convRate +
                ", taxRate=" + taxRate +
                ", b2sTaxRate=" + b2sTaxRate +
                ", b2sItemMargin=" + b2sItemMargin +
                ", varItemMargin=" + varItemMargin +
                ", b2sShippingMargin=" + b2sShippingMargin +
                ", varShippingMargin=" + varShippingMargin +
                ", itemPoints=" + itemPoints +
                ", taxPoints=" + taxPoints +
                ", b2sTaxPoints=" + b2sTaxPoints +
                ", shippingPoints=" + shippingPoints +
                ", orderLinePoints=" + orderLinePoints +
                ", b2sItemProfitPrice=" + b2sItemProfitPrice +
                ", b2sTaxProfitPrice=" + b2sTaxProfitPrice +
                ", b2sShippingProfitPrice=" + b2sShippingProfitPrice +
                ", varItemProfitPrice=" + varItemProfitPrice +
                ", varTaxProfitPrice=" + varTaxProfitPrice +
                ", varShippingProfitPrice=" + varShippingProfitPrice +
                ", varOrderLinePrice=" + varOrderLinePrice +
                ", comment='" + comment + '\'' +
                ", createDate=" + createDate +
                ", orderStatus=" + orderStatus +
                ", orderLineType='" + orderLineType + '\'' +
                ", orderSource='" + orderSource + '\'' +
                ", policyId='" + policyId + '\'' +
                ", policy='" + policy + '\'' +
                ", travelStartDate=" + travelStartDate +
                ", travelEndDate=" + travelEndDate +
                ", bookingQuantity=" + bookingQuantity +
                ", b2sOnlineFee=" + b2sOnlineFee +
                ", b2sOfflineFee=" + b2sOfflineFee +
                ", orderLineUndiscountedUnitFee=" + orderLineUndiscountedUnitFee +
                ", notificationId=" + notificationId +
                ", taxes=" + taxes +
                ", fees=" + fees +
                ", itemPriceOriginal=" + itemPriceOriginal +
                ", brand='" + brand + '\'' +
                ", manufacturer='" + manufacturer + '\'' +
                ", upc='" + upc + '\'' +
                ", categoryPath='" + categoryPath + '\'' +
                ", merchantId='" + merchantId + '\'' +
                ", sku='" + sku + '\'' +
                ", shippingMethod='" + shippingMethod + '\'' +
                ", sellerId='" + sellerId + '\'' +
                ", listingId='" + listingId + '\'' +
                ", storeId='" + storeId + '\'' +
                ", store=" + store +
                ", payrollAmount=" + payrollAmount +
                '}';
    }
}