package com.b2s.db.model;

public class OrderLineKey {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_line.line_num
     *
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    private Integer lineNum;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_line.order_id
     *
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    private Long orderId;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_line.line_num
     *
     * @return the value of order_line.line_num
     *
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    public Integer getLineNum() {
        return lineNum;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_line.line_num
     *
     * @param lineNum the value for order_line.line_num
     *
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    public void setLineNum(Integer lineNum) {
        this.lineNum = lineNum;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_line.order_id
     *
     * @return the value of order_line.order_id
     *
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_line.order_id
     *
     * @param orderId the value for order_line.order_id
     *
     * @abatorgenerated Thu Jan 11 18:53:08 EST 2007
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    @Override
    @SuppressWarnings("unchecked")
    public boolean equals(final Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {return false;}

        final OrderLineKey otherKey = (OrderLineKey) o;

        if (lineNum != null ? !lineNum.equals(otherKey.lineNum) : otherKey.lineNum != null) {
            return false;
        }

        if (orderId != null ? !orderId.equals(otherKey.orderId) : otherKey.orderId != null) {
            return false;
        }

        return true;
    }

    @Override
    public int hashCode() {
        int result = lineNum != null ? lineNum.hashCode() : 0;
        result = 31 * result + (orderId != null ? orderId.hashCode() : 0);
        return result;
    }
}