INSERT INTO order_status VALUES (-2, 'Started');
INSERT INTO order_status VALUES (-1, 'Submitting to Order Service');
INSERT INTO order_status VALUES (0, 'Processing');
INSERT INTO order_status VALUES (1, 'Ordered');
INSERT INTO order_status VALUES (2, 'Shipped');
INSERT INTO order_status VALUES (3, 'Completed');
INSERT INTO order_status VALUES (4, 'Refund Pending');
INSERT INTO order_status VALUES (5, 'ReturnRequested');
INSERT INTO order_status VALUES (6, 'Cmplt-Returned');
INSERT INTO order_status VALUES (7, 'Cmplt-Cancelled');
INSERT INTO order_status VALUES (8, 'Processed');
INSERT INTO order_status VALUES (9, 'Cmplt-NLA');
INSERT INTO order_status VALUES (10, 'OrderPending');
INSERT INTO order_status VALUES (11, 'Demo');
INSERT INTO order_status VALUES (12, 'Reprocess - Full');
INSERT INTO order_status VALUES (14, 'Cmplt-BadAddr');
INSERT INTO order_status VALUES (15, 'Cmplt-Refused');
INSERT INTO order_status VALUES (16, 'Reprocess - Partial');
INSERT INTO order_status VALUES (18, 'BackOrder');
INSERT INTO order_status VALUES (19, 'ReProcessPending');
INSERT INTO order_status VALUES (20, 'Delayed Delivery');
INSERT INTO order_status VALUES (21, 'Order Line Adjustment');
INSERT INTO order_status VALUES (22, 'Cmplt-Unshippable');
INSERT INTO order_status VALUES (23, 'Backorder Review');
INSERT INTO order_status VALUES (24, 'Ordered-PickupAvailable');
INSERT INTO order_status VALUES (25, 'Completed-ReturnStrCrdt');
INSERT INTO order_status VALUES (26, 'RSL Requested');
INSERT INTO order_status VALUES (27, 'RSL Forwarded');
INSERT INTO order_status VALUES (28, 'RSL Used');
INSERT INTO order_status VALUES (29, 'RSL Vdr Recd Item');
INSERT INTO order_status VALUES (30, 'RSL Pnd Vdr Rfnd');
INSERT INTO order_status VALUES (31, 'Cmplt-RSL Expired');
INSERT INTO order_status VALUES (32, 'Cmplt-RTNW Closed');
INSERT INTO order_status VALUES (33, 'Cmplt-Conven Rtn');
INSERT INTO order_status VALUES (34, 'Cmplt-Not Recd');
INSERT INTO order_status VALUES (35, 'Cmplt-Rtn Damaged');
INSERT INTO order_status VALUES (36, 'Cmplt-Rtn Wrong Item');
INSERT INTO order_status VALUES (37, 'Cmplt-GC Not Recd');
INSERT INTO order_status VALUES (38, 'Cmplt-GC Reship Req');
INSERT INTO order_status VALUES (39, 'Cmplt-PofP Fwrd');
INSERT INTO order_status VALUES (40, 'Ticketing');
INSERT INTO order_status VALUES (42, 'On Hold');
INSERT INTO order_status VALUES (43, 'Delivered');
INSERT INTO order_status VALUES (97, 'Killed');
INSERT INTO order_status VALUES (98, 'Fraud - Alert');
INSERT INTO order_status VALUES (99, 'Failed');

INSERT INTO order_line_status_history (order_id,line_num,status_id,date_time) VALUES (3,1,0,{ts '2018-11-10 05:08:25.303'});
INSERT INTO order_line_status_history (order_id,line_num,status_id,date_time) VALUES (3,1,1,{ts '2018-11-11 05:06:16.147'});
INSERT INTO order_line_status_history (order_id,line_num,status_id,date_time) VALUES (3,1,6,{ts '2018-11-12 05:08:08.740'});
INSERT INTO order_line_status_history (order_id,line_num,status_id,date_time) VALUES (3,1,21,{ts '2018-11-13 05:08:08.747'});