import { Offer } from '@app/models/offer';
import { Option } from '@app/models/option';
import { AdditionalInfo } from '@app/models/additional-info';
import { ImageURLs } from '@app/models/image-urls';;
import { MerchantSpecificInfo } from '@app/models/merchant-specific-info';
import { OptionsConfigurationData } from '@app/models/options-configuration';
import { Engrave } from '@app/models/engrave';
import { AddOns } from '@app/models/addOns';
import { SmartPrice } from '@app/models/smart-price';
import { Promotion } from '@app/models/promotion';
import { Category } from '@app/models/category';

export interface Product {
  psid: string;
  sku: string;
  name: string;
  shortDescription: string;
  longDescription?: string;
  brand: string;
  manufacturer: string;
  averageRating: number;
  upc: string;
  shippingAvailabilityMessage?: string;
  shipmentQuoteDate?: string;
  promotion?: Promotion;
  categories: Category[];
  offers: Offer[];
  options?: Option[];
  additionalInfo?: AdditionalInfo;
  images: ImageURLs;
  variations?: Product[];
  available: boolean;
  appleSku?: string;
  merchantSpecificData?: MerchantSpecificInfo;
  accessoryItem: boolean;
  optionsConfigurationData?: OptionsConfigurationData;
  hasVariations: boolean;
  isEligibleForGift: boolean;
  availableGiftItems?: Product[];
  isMultiGiftAvailable: boolean;
  isEngravable: boolean;
  engrave?: Engrave;
  defaultOffer: Offer;
  hasOffers: boolean;
  productBasedPricingKey: string;
  addOns: AddOns;
  quantity?: number;
  selected?: boolean;
  learnMore: string;
  hasRelatedProduct?: boolean;
  relatedProducts?: Product[];
  carouselImages?: Array<string>;
  smartPrice?: SmartPrice;
}
