import { Program } from '@app/models/program';
import { Address } from '@app/models/address';
import { DiscountCode } from '@app/models/discount-code';
import { AdditionalInfo } from '@app/models/additional-info';

export interface User {
  programid: string;
  userid: string;
  varid: string;
  password: string;
  points: number;
  firstName: string;
  lastName: string;
  addr1: string;
  addr2: string;
  city: string;
  state: string;
  zip: string;
  country: string;
  phone: string;
  email: string;
  category?: string;
  isAdmin: boolean;
  browseOnly: boolean;
  businessName?: string;
  clientIpAdress: string;
  sessionId: string;
  sid?: string;
  csid?: string;
  billTo?: Address;
  shipTo?: Address;
  discounts?: Array<DiscountCode>;
  isEligibleForPayrollDeduction: boolean;
  addresses?: Array<Address>;
  hostName: string;
  employerId?: number;
  employerName?: string;
  loginType: string;
  pricingTier: string;
  anonymous: boolean;
  matomoTrackerURL: string;
  matomoSiteId: string;
  analytics: Array<string>;
  initialUserBalance: number;
  deceased: boolean;
  additionalInfo: AdditionalInfo;
  imageURL: string;
  proxyUser: boolean;
  proxyUserId?: number;
  locale: string;
  configInfos: object;
  randomId?: string;
  fullName: string;
  varId: string;
  userId: string;
  ipaddress: string;
  addressPresent: boolean;
  amexInstallment: boolean;
  processStep: number;
  programId: string;
  supplierId: number;
  balance: number;
  eligibleForDiscount: boolean;
  program: Program;
  overrideShipping?: boolean;
  awpEmployeeGroup?: boolean;
  awpPayrollEnabled?: boolean;
  agentId?: string;
  agentBrowse: boolean;
  navflag: string;
  varName: string;
  hashedUserId: string;
  analyticsWindow?: object;
  analyticsUrl?: string;
  sessionUserInfo?: { [key: string]:  string };
  sessionState?: string;
  headerName?: string;
}
